# NUMPY 
# It is a library in python which is use for array

In [ ]:
# NumPy is an open source Python package for scientific computing.
# NumPy supports large, multidimensional arrays and matrices.
# NumPy arrays are faster compared to Python lists.

(List to array) :

In [1]:
import numpy as np

In [2]:
l=[1,2,3]                                   #1dimensional

In [3]:
arr=np.array(l)                          # to convert list to array

In [4]:
arr

array([1, 2, 3])

In [5]:
z=[11,4,0.9]

In [6]:
arr1=np.array(z)

In [7]:
arr1                                     #converted all values to float... bcoz there is one float value in z

array([11. ,  4. ,  0.9])

In [8]:
type(arr)                #checking type

numpy.ndarray

In [9]:
type(arr1)

numpy.ndarray

In [10]:
arr.size       # always check size and shape of an array it will be helpful.

3

In [11]:
arr.shape               #checking shape

(3,)

In [12]:
np.ndim(arr)                # checking dimension

1

In [13]:
sum(l)            # addition of an array 

6

In [14]:
sum(z)

15.9

In [ ]:
# 2 Dimensional array

In [15]:
l1=[[1,2,3],[4,5,6],[7,8,9]]                            #2d

In [16]:
arr2=np.array(l1)               # to convert list to array

In [17]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr2.size

9

In [19]:
sum(arr2)

array([12, 15, 18])

In [20]:
arr2.shape

(3, 3)

In [21]:
np.ndim(arr2)

2

# for reshape

In [22]:
arr2.shape          # for reshaping first check the o/g shape of array that will be useful

(3, 3)

In [23]:
arr3=arr2.reshape(1,9)    # reshaping an array

In [24]:
arr3

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [25]:
arr4=arr2.reshape(9,1)

In [26]:
arr4

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

# for .arange

In [ ]:
# Values are generated within the half-open interval (start, stop) 

In [27]:
arr5=np.arange(1,10)        # np.arange 

In [28]:
arr5

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr5.size

9

In [30]:
arr5.shape

(9,)

In [31]:
arr6=arr5.reshape(3,3)

In [32]:
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr6.shape

(3, 3)

In [34]:
arr6.size

9

# np.zeros

In [ ]:
# This Function enables you to create NumPy arrays that contain only zeros.

In [35]:
np.zeros((2,3))              # here 2 defines row and 3 columns # before comma , it will always rows and after comma , columns

array([[0., 0., 0.],
       [0., 0., 0.]])

# np.ones

In [ ]:
# This function returns a new array of given shape and data type, where the element's value is set to 1.

In [36]:
np.ones((5,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# np.eye

In [ ]:
# The numpy. eye() method returns an array of shape, R x C.
# where all elements are equal to zero, except for the kth diagonal, whose values are equal to one.

In [37]:
np.eye(4)       # 4 indicates size of matrix... size can be anything as per our wish

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# np.linspace

In [ ]:
# It is used for creating numeric sequences.
# It's somewhat similar to the NumPy arange function, in that it creates sequences of evenly spaced numbers.

In [38]:
np.linspace(0,10,7)      #divides into equal parts 

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [39]:
np.linspace(1,7,7)

array([1., 2., 3., 4., 5., 6., 7.])

In [40]:
np.linspace(1,6,8)

array([1.        , 1.71428571, 2.42857143, 3.14285714, 3.85714286,
       4.57142857, 5.28571429, 6.        ])

In [41]:
np.linspace(1,6,2)

array([1., 6.])

In [42]:
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

# np.random.rand     (For Normal)

In [ ]:
# It returns an array of specified shape and fills it with random integers from low (inclusive) to high (exclusive),
# i.e. in the interval [low, high).

In [43]:
np.random.rand(3,4)                 # 3row 4column

array([[0.10166078, 0.09738664, 0.47189148, 0.03935107],
       [0.31410236, 0.1432662 , 0.82873754, 0.93646252],
       [0.32083343, 0.89922567, 0.63938968, 0.53996816]])

In [44]:
np.random.rand(2,3)

array([[0.49447284, 0.00864564, 0.79817374],
       [0.43395927, 0.79121652, 0.34842481]])

# np.random.randn (For Normal Distribution)

In [ ]:
# This function return a sample (or samples) from the “standard normal” distribution.

In [45]:
np.random.randn(2,3)               #for normal distribution: part of statistics

array([[ 1.85879991, -0.14277375, -1.97183817],
       [ 0.92539904,  0.90888257, -0.10169495]])

# np.random.randint (Only Integers values)

In [ ]:
#  for doing random sampling in numpy.
# It returns an array of specified shape and fills it with random integers from low (inclusive) to high (exclusive).

In [46]:
np.random.randint(4,40,20)    #it will take any 20 random numbers between 4(inclusive) and 40(exclusive)

array([ 6, 29, 11, 13, 23, 15,  7, 37, 29, 11, 12, 32, 18, 31, 11, 33, 32,
       14, 26,  8])

In [47]:
np.random.randint(50,size=(3,4))         #2dimensional....limited to 0(included) to 50(excluded)....

array([[32, 35, 49, 23],
       [39, 36, 28,  5],
       [42, 11, 25, 17]])

float values will not be considered

In [48]:
np.random.randint(-2,20,10)

array([17, 16, 12,  1, -1, 18, -1, -1, 15,  2])

In [49]:
np.random.randint(-50,0,size=(3,4))    

array([[-12, -17, -32,  -2],
       [-42, -47,  -4, -40],
       [-14, -18, -49, -30]])

Revision


In [50]:
a1=[[30,40,50,60],[13,23,33,43],[0,1,2,3],[100,200,300,400]]

In [51]:
arr9=np.array(a1)

In [52]:
arr9

array([[ 30,  40,  50,  60],
       [ 13,  23,  33,  43],
       [  0,   1,   2,   3],
       [100, 200, 300, 400]])

In [53]:
arr9.shape

(4, 4)

In [54]:
arr9.size

16

In [55]:
np.ndim(arr9)

2

In [56]:
sum(arr9)                      #does addition column wise

array([143, 264, 385, 506])

# Another method to make array

In [57]:
import numpy as np

In [58]:
l=[30,40,50,60,13,23,33,43,0,1,2,3,100,200,300,400]

In [59]:
arr10=np.array(l)

In [60]:
arr10

array([ 30,  40,  50,  60,  13,  23,  33,  43,   0,   1,   2,   3, 100,
       200, 300, 400])

In [61]:
arr10.shape

(16,)

In [62]:
arr11=arr10.reshape(4,4)

In [63]:
arr11

array([[ 30,  40,  50,  60],
       [ 13,  23,  33,  43],
       [  0,   1,   2,   3],
       [100, 200, 300, 400]])

In [64]:
np.ndim(arr11)

2

# to convert 1D to 2D we use reshapping function

In [65]:
arr11[0,0]   #indexing[R,C]    # oth row oth cloumn

30

In [66]:
arr11[1,1]                   #1st row 1st column

23

In [67]:
arr11[:,:]                     # full array

array([[ 30,  40,  50,  60],
       [ 13,  23,  33,  43],
       [  0,   1,   2,   3],
       [100, 200, 300, 400]])

In [68]:
arr11[0:2,1:3]         # filtering indexing

array([[40, 50],
       [23, 33]])

In [69]:
arr11[1:3,2:]

array([[33, 43],
       [ 2,  3]])

In [70]:
arr11[:,1:3]

array([[ 40,  50],
       [ 23,  33],
       [  1,   2],
       [200, 300]])

In [71]:
arr11[2:,2:]

array([[  2,   3],
       [300, 400]])

# EMPTY COLUMN

In [72]:
arr11[0:2,]             #for empty column it will give the o/p

array([[30, 40, 50, 60],
       [13, 23, 33, 43]])

# EMPTY ROW

In [73]:
arr11[,0:2]           #for empty row it will not give o/p (must define column)

SyntaxError: invalid syntax (<ipython-input-73-9e1d634e94d2>, line 1)

In [74]:
arr11[:,0:2]      #correction to previous error

array([[ 30,  40],
       [ 13,  23],
       [  0,   1],
       [100, 200]])

# Tricky 

In [75]:
arr11.sum()

1298

In [76]:
arr11

array([[ 30,  40,  50,  60],
       [ 13,  23,  33,  43],
       [  0,   1,   2,   3],
       [100, 200, 300, 400]])

In [77]:
arr11[[0,2],[0,3]]   # [0,2] [0,3] 0,0 are for row & column and they are compared, similarly 2,3 are for row & column. 

array([30,  3])

# Operators For Array

In [78]:
a=[1,2,3,4]

In [79]:
b=[5,6,7,8]

In [80]:
arr12=np.array(a)

In [81]:
arr12

array([1, 2, 3, 4])

In [82]:
arr13=arr12.reshape(2,2)

In [83]:
arr13

array([[1, 2],
       [3, 4]])

In [84]:
arr14=np.array(b)

In [85]:
arr14

array([5, 6, 7, 8])

In [86]:
arr15=arr14.reshape(2,2)

In [87]:
arr15

array([[5, 6],
       [7, 8]])

In [88]:
arr13.shape

(2, 2)

In [89]:
arr15.shape

(2, 2)

In [90]:
arr13.size

4

In [91]:
arr15.size

4

In [92]:
c=np.add(arr13,arr15)   #Add

In [93]:
c

array([[ 6,  8],
       [10, 12]])

In [94]:
c=np.+(arr13,arr15) #symbols of operators can't be used with (np.) as it will give error

SyntaxError: invalid syntax (<ipython-input-94-06147ca7c360>, line 1)

In [95]:
c=(arr13+arr15)    # But symbols of operator can be use between arrays

In [96]:
c

array([[ 6,  8],
       [10, 12]])

In [97]:
c=np.subtract(arr13,arr15)   #Subtract

In [98]:
c

array([[-4, -4],
       [-4, -4]])

In [99]:
c=np.multiply(arr13,arr15)   #Multiply

In [100]:
c

array([[ 5, 12],
       [21, 32]])

In [101]:
c=np.divide(arr13,arr15)   #Divide

In [102]:
c

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [103]:
arr13/arr15       

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

# Alternate method for operators 

In [104]:
arr13==arr15      # == indicates equals to

array([[False, False],
       [False, False]])

In [105]:
arr13!=arr15   # != indicates not equals to

array([[ True,  True],
       [ True,  True]])

In [106]:
arr13<2     #Checking Conditions  (True or False)

array([[ True, False],
       [False, False]])

In [107]:
arr15<2

array([[False, False],
       [False, False]])

In [108]:
arr13<arr15

array([[ True,  True],
       [ True,  True]])

# a.ravel will convert any dimensional to 1D

In [109]:
arr13   

array([[1, 2],
       [3, 4]])

In [110]:
arr13.ravel()

array([1, 2, 3, 4])

# Filtering in Array

In [111]:
arr13

array([[1, 2],
       [3, 4]])

In [112]:
arr13[arr13<3]

array([1, 2])

In [113]:
arr13[arr13==4]

array([4])

In [114]:
arr13[arr13>3]

array([4])

In [115]:
arr13[arr13!=4]

array([1, 2, 3])

# Gapping

In [116]:
l=[1,2,3,4,5,6,7,8,9,10]

In [117]:
l[0:9:2]

[1, 3, 5, 7, 9]

# np.unique(arr) --- It will avoid all the duplicates in an array

In [118]:
np.unique(arr13)          #similar to set

array([1, 2, 3, 4])

In [120]:
import numpy as np

In [121]:
t=[1,2,3,4,4,4,5,6,6,7,7,7,8,9,9,9]

In [122]:
t

[1, 2, 3, 4, 4, 4, 5, 6, 6, 7, 7, 7, 8, 9, 9, 9]

In [123]:
arr14=np.array(t)

In [124]:
arr14

array([1, 2, 3, 4, 4, 4, 5, 6, 6, 7, 7, 7, 8, 9, 9, 9])

In [125]:
arr14.shape

(16,)

In [126]:
np.unique(arr14)               #it will avoid all the duplicates

array([1, 2, 3, 4, 5, 6, 7, 8, 9])