# Pandas 

In [1]:
import pandas as pd

In [2]:
d={'Name':['T','M','K'],'Age':[9,8,7],'Gender':['M','F','M'],'Salary':[40,50,60],'Occupation':['DA','DE','DS'],'Purchasing':['Yes','Yes','No']}

In [3]:
d

{'Name': ['T', 'M', 'K'],
 'Age': [9, 8, 7],
 'Gender': ['M', 'F', 'M'],
 'Salary': [40, 50, 60],
 'Occupation': ['DA', 'DE', 'DS'],
 'Purchasing': ['Yes', 'Yes', 'No']}

In [4]:
df=pd.DataFrame(d)

In [5]:
df

Name  Age Gender  Salary Occupation Purchasing
0    T    9      M      40         DA        Yes
1    M    8      F      50         DE        Yes
2    K    7      M      60         DS         No

# Filtering in Pandas

In [6]:
df[df['Purchasing']=='Yes']     #Filtering

Name  Age Gender  Salary Occupation Purchasing
0    T    9      M      40         DA        Yes
1    M    8      F      50         DE        Yes

In [7]:
df.dtypes

Name          object
Age            int64
Gender        object
Salary         int64
Occupation    object
Purchasing    object
dtype: object

# Filtering using Logical operators

In [8]:
df[(df['Gender']=='F')& (df['Purchasing']=='Yes')]    #Filtering using logical operator

Name  Age Gender  Salary Occupation Purchasing
1    M    8      F      50         DE        Yes

In [9]:
type(df)

pandas.core.frame.DataFrame

In [10]:
df['Salary']   #checking values of column salary

0    40
1    50
2    60
Name: Salary, dtype: int64

In [11]:
type(df['Salary'])   #checking type

pandas.core.series.Series

In [12]:
type(df[['Name','Age']])         #combination of series, therefore dataframe

pandas.core.frame.DataFrame

In [ ]:
# One column in a frame is called as a series.
# More than one column in a frame is called as a DataFrame

In [13]:
df

Name  Age Gender  Salary Occupation Purchasing
0    T    9      M      40         DA        Yes
1    M    8      F      50         DE        Yes
2    K    7      M      60         DS         No

# For Adding another column or series in a same data frame

In [14]:
l2=[1,2,3]

In [15]:
s=pd.Series(l2)

In [16]:
s

0    1
1    2
2    3
dtype: int64

In [17]:
df['ID']=s

In [18]:
df      

Name  Age Gender  Salary Occupation Purchasing  ID
0    T    9      M      40         DA        Yes   1
1    M    8      F      50         DE        Yes   2
2    K    7      M      60         DS         No   3

# Sort values
Pandas sort_values() function sorts a data frame in Ascending or Descending order of passed Column

# 1) for list

In [19]:
a=[5,6,7,8,9]       

In [20]:
a.sort(reverse=True)

In [23]:
a

[9, 8, 7, 6, 5]

# 2) for 1d array

In [24]:
import numpy as np      

In [25]:
arr1=np.array(a)

In [26]:
arr1

array([9, 8, 7, 6, 5])

In [27]:
arr1.sort()

In [28]:
arr1

array([5, 6, 7, 8, 9])

# 3) for 2D array

In [29]:
a=[3,2,1,6,5,4]

In [30]:
a

[3, 2, 1, 6, 5, 4]

In [31]:
arr=np.array(a).reshape(2,3)

In [32]:
arr

array([[3, 2, 1],
       [6, 5, 4]])

In [33]:
arr.sort()

In [34]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

# 4) for DataFrame

In [35]:
df

Name  Age Gender  Salary Occupation Purchasing  ID
0    T    9      M      40         DA        Yes   1
1    M    8      F      50         DE        Yes   2
2    K    7      M      60         DS         No   3

In [36]:
df['Age'].sort_values()

2    7
1    8
0    9
Name: Age, dtype: int64

In [37]:
df['Age'].sort_values(ascending=False)   #for descending but this should not be used

0    9
1    8
2    7
Name: Age, dtype: int64

# All the columns value has been changed from the original one #this is very main

In [38]:
b=df.sort_values('Age') 

In [39]:
b

Name  Age Gender  Salary Occupation Purchasing  ID
2    K    7      M      60         DS         No   3
1    M    8      F      50         DE        Yes   2
0    T    9      M      40         DA        Yes   1

In [40]:
df           #original one

Name  Age Gender  Salary Occupation Purchasing  ID
0    T    9      M      40         DA        Yes   1
1    M    8      F      50         DE        Yes   2
2    K    7      M      60         DS         No   3

# For Setting Index

In [41]:
c=df.set_index('ID')

In [42]:
c

Name  Age Gender  Salary Occupation Purchasing
ID                                               
1     T    9      M      40         DA        Yes
2     M    8      F      50         DE        Yes
3     K    7      M      60         DS         No

In [43]:
c.columns     #now ID will no longer be column as it has become index

Index(['Name', 'Age', 'Gender', 'Salary', 'Occupation', 'Purchasing'], dtype='object')

# For Resetting Index

In [44]:
d=df.reset_index()   #now it will recall index value by its own and make ID as a column

In [45]:
d

index Name  Age Gender  Salary Occupation Purchasing  ID
0      0    T    9      M      40         DA        Yes   1
1      1    M    8      F      50         DE        Yes   2
2      2    K    7      M      60         DS         No   3

# Advance Topic of Pandas 
# 1. PIVOT

In [46]:
data={'A':['foo','foo','foo','bar','bar','bar'],
      'B':['one','one','two','two','one','one'],
      'C':['x','y','x','y','x','y'],
      'D':[1,3,2,5,4,1]
     }

In [47]:
data

{'A': ['foo', 'foo', 'foo', 'bar', 'bar', 'bar'],
 'B': ['one', 'one', 'two', 'two', 'one', 'one'],
 'C': ['x', 'y', 'x', 'y', 'x', 'y'],
 'D': [1, 3, 2, 5, 4, 1]}

In [48]:
df2=pd.DataFrame(data)

In [49]:
df2

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [50]:
df3=pivot_df2=df2.pivot_table(values='D',index='A',columns=['C'],aggfunc=np.sum)

In [51]:
df3

C    x  y
A        
bar  4  6
foo  3  3

In [52]:
df4=pivot_df2=df2.pivot_table(values='D',index='A',columns=['C','B'],aggfunc=np.sum)

In [53]:
df4     # NaN - it does not contain any value in Data Frame... (bar x two dosen't have any value in frame)

C      x         y     
B    one  two  one  two
A                      
bar  4.0  NaN  1.0  5.0
foo  1.0  2.0  3.0  NaN

In [54]:
z=df2.reset_index()    #For resetting

In [55]:
z        

index    A    B  C  D
0      0  foo  one  x  1
1      1  foo  one  y  3
2      2  foo  two  x  2
3      3  bar  two  y  5
4      4  bar  one  x  4
5      5  bar  one  y  1